import { useEffect, useMemo, useState, type ButtonHTMLAttributes } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Archive, BookOpen, Check, ChevronRight, CircleDot, Download, Inbox, LayoutGrid, List, Menu, Moon, MoreHorizontal, Play, Plus, Search, Settings, Sun, Users, X } from "lucide-react";
import { createDigest, createExport, getWorkspace, ingestLatestRun, updateItem, updateWatcher } from "./api";
import { demoState } from "./demo-data";
import { cn, relativeTime } from "./lib";
import type { Signal, WorkspaceState } from "./types";

type View = "inbox" | "watchers" | "digests" | "operations" | "members" | "exports" | "settings";
const nav: Array<[View, string, typeof Inbox]> = [["inbox", "Inbox", Inbox], ["watchers", "Watchers", CircleDot], ["digests", "Digests", BookOpen], ["operations", "Operations", Play], ["members", "Members", Users], ["exports", "Exports", Download]];

function Button({ children, className, variant = "default", ...props }: ButtonHTMLAttributes<HTMLButtonElement> & { variant?: "default" | "quiet" | "accent" }) {
  return <button className={cn("inline-flex h-9 items-center justify-center gap-2 rounded-lg px-3 text-sm font-medium transition-colors disabled:opacity-45", variant === "accent" ? "bg-accent text-white hover:brightness-95" : variant === "quiet" ? "text-muted hover:bg-ink/5 hover:text-ink" : "border bg-surface hover:bg-ink/[.035]", className)} {...props}>{children}</button>;
}

export function App() {
  const [view, setView] = useState<View>("inbox");
  const [selected, setSelected] = useState<string | null>(null);
  const [watcher, setWatcher] = useState("all");
  const [inboxStatus, setInboxStatus] = useState<"active" | "new" | "saved" | "dismissed">("active");
  const [query, setQuery] = useState("");
  const [layout, setLayout] = useState<"list" | "grid">(() => (localStorage.getItem("tekt-layout") as "list" | "grid") || "list");
  const [mobileNav, setMobileNav] = useState(false);
  const [dark, setDark] = useState(() => localStorage.getItem("tekt-theme") === "dark");
  const result = useQuery({ queryKey: ["workspace"], queryFn: getWorkspace });
  const data = result.data ?? demoState;
  const usingDemo = result.isError;

  useEffect(() => { document.documentElement.classList.toggle("dark", dark); localStorage.setItem("tekt-theme", dark ? "dark" : "light"); }, [dark]);
  useEffect(() => { localStorage.setItem("tekt-layout", layout); }, [layout]);
  useEffect(() => {
    const handler = (event: KeyboardEvent) => {
      if (event.key === "/" && !(event.target instanceof HTMLInputElement)) { event.preventDefault(); document.getElementById("signal-search")?.focus(); }
      if (event.key === "Escape") { setSelected(null); setMobileNav(false); }
    };
    window.addEventListener("keydown", handler); return () => window.removeEventListener("keydown", handler);
  }, []);

  const filtered = useMemo(() => data.items.filter((item) => (watcher === "all" || item.watcher === watcher) && (inboxStatus === "active" ? item.status !== "dismissed" : item.status === inboxStatus) && `${item.title} ${item.description} ${item.topic}`.toLowerCase().includes(query.toLowerCase())), [data.items, watcher, inboxStatus, query]);
  const selectedItem = data.items.find((item) => item.id === selected) ?? null;

  return <div className="min-h-screen lg:grid lg:grid-cols-[244px_minmax(0,1fr)]">
    <Sidebar data={data} view={view} setView={(next) => { setView(next); setMobileNav(false); }} open={mobileNav} close={() => setMobileNav(false)} />
    <main className="min-w-0">
      <header className="sticky top-0 z-20 flex h-16 items-center border-b bg-canvas/90 px-4 backdrop-blur-md sm:px-7">
        <Button variant="quiet" className="mr-2 px-2 lg:hidden" aria-label="Open navigation" onClick={() => setMobileNav(true)}><Menu size={19}/></Button>
        <div className="min-w-0 flex-1"><p className="truncate text-sm font-medium">{data.workspace.name}</p><p className="text-xs text-muted">{usingDemo ? "Starter workspace · local API is starting" : `Revision ${data.workspace.revision} · all changes saved`}</p></div>
        <Button variant="quiet" className="px-2" aria-label="Toggle theme" onClick={() => setDark(!dark)}>{dark ? <Sun size={17}/> : <Moon size={17}/>}</Button>
      </header>
      {view === "inbox" && <InboxView data={data} filtered={filtered} watcher={watcher} setWatcher={setWatcher} inboxStatus={inboxStatus} setInboxStatus={setInboxStatus} query={query} setQuery={setQuery} select={setSelected} live={!usingDemo} layout={layout} setLayout={setLayout} />}
      {view === "watchers" && <WatchersView data={data} live={!usingDemo} />}
      {view === "digests" && <DigestsView data={data} live={!usingDemo} />}
      {view === "operations" && <OperationsView data={data} />}
      {view === "members" && <MembersView />}
      {view === "exports" && <ExportsView data={data} live={!usingDemo} />}
      {view === "settings" && <SettingsView dark={dark} setDark={setDark} />}
    </main>
    {selectedItem && <Detail item={selectedItem} close={() => setSelected(null)} live={!usingDemo} />}
  </div>;
}

function Sidebar({ data, view, setView, open, close }: { data: WorkspaceState; view: View; setView: (v: View) => void; open: boolean; close: () => void }) {
  return <><div className={cn("fixed inset-0 z-30 bg-black/25 backdrop-blur-sm lg:hidden", open ? "block" : "hidden")} onClick={close}/><aside className={cn("fixed inset-y-0 left-0 z-40 flex w-[276px] flex-col border-r bg-surface p-3 transition-transform lg:sticky lg:top-0 lg:z-auto lg:h-screen lg:w-auto lg:translate-x-0", open ? "translate-x-0" : "-translate-x-full")}>
    <div className="flex h-12 items-center gap-2 px-2"><div className="grid h-7 w-7 place-items-center rounded-lg bg-ink text-xs font-semibold text-canvas">t.</div><span className="font-serif text-lg font-semibold tracking-tight">tekt.observer</span><Button variant="quiet" className="ml-auto px-2 lg:hidden" onClick={close}><X size={18}/></Button></div>
    <nav className="mt-4 space-y-1" aria-label="Workspace">
      {nav.map(([id, label, Icon]) => <button key={id} onClick={() => setView(id)} className={cn("flex w-full items-center gap-3 rounded-lg px-3 py-2 text-left text-sm transition-colors", view === id ? "bg-ink/[.07] font-medium text-ink" : "text-muted hover:bg-ink/[.04] hover:text-ink")}><Icon size={17}/><span>{label}</span>{id === "inbox" && <span className="ml-auto rounded-full bg-ink/[.07] px-2 py-0.5 text-[11px]">{data.items.filter(i => i.status === "new").length}</span>}</button>)}
    </nav>
    <div className="mt-6 px-3 text-[11px] font-semibold uppercase tracking-[.14em] text-muted">Watchers</div>
    <div className="mt-2 space-y-1">{data.watchers.map((item) => <button key={item.id} onClick={() => setView("watchers")} className="flex w-full items-center gap-3 rounded-lg px-3 py-2 text-left text-sm text-muted hover:bg-ink/[.04] hover:text-ink"><span className={cn("h-2 w-2 rounded-full", item.status === "paused" ? "bg-slate-400" : item.status === "attention" ? "bg-amber-500" : "bg-emerald-500")}/><span className="truncate">{item.name}</span></button>)}</div>
    <div className="mt-auto border-t pt-3"><button onClick={() => setView("settings")} className="flex w-full items-center gap-3 rounded-lg px-3 py-2 text-sm text-muted hover:bg-ink/[.04] hover:text-ink"><Settings size={17}/>Settings</button><div className="mt-1 flex items-center gap-3 px-3 py-2"><div className="grid h-8 w-8 place-items-center rounded-full bg-accent/15 text-xs font-semibold text-accent">YO</div><div className="min-w-0"><p className="truncate text-xs font-medium">Local owner</p><p className="text-[11px] text-muted">Owner</p></div><MoreHorizontal className="ml-auto text-muted" size={16}/></div></div>
  </aside></>;
}

function InboxView({ data, filtered, watcher, setWatcher, inboxStatus, setInboxStatus, query, setQuery, select, live, layout, setLayout }: { data: WorkspaceState; filtered: Signal[]; watcher: string; setWatcher: (v: string) => void; inboxStatus: "active" | "new" | "saved" | "dismissed"; setInboxStatus: (v: "active" | "new" | "saved" | "dismissed") => void; query: string; setQuery: (v: string) => void; select: (v: string) => void; live: boolean; layout: "list" | "grid"; setLayout: (v: "list" | "grid") => void }) {
  const queryClient = useQueryClient(); const ingest = useMutation({ mutationFn: () => live ? ingestLatestRun() : Promise.reject(new Error("Start the local app first")), onSuccess: () => queryClient.invalidateQueries({ queryKey: ["workspace"] }) });
  return <section className="mx-auto max-w-6xl px-4 py-8 sm:px-7 sm:py-12"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-[.16em] text-accent">Unified signals</p><h1 className="mt-2 font-serif text-4xl font-semibold tracking-tight sm:text-5xl">Your inbox</h1><p className="mt-3 max-w-xl text-sm leading-6 text-muted">A focused view of what changed across everything you observe.</p></div><Button variant="accent" onClick={() => ingest.mutate()} disabled={ingest.isPending}>{ingest.isPending ? "Connecting…" : "Load latest run"}</Button></div>{ingest.isError && <p role="alert" className="mt-4 rounded-lg bg-red-500/10 p-3 text-sm text-red-700">{ingest.error.message}</p>}
    <div className="mt-8 flex gap-1 overflow-x-auto border-b" role="tablist" aria-label="Inbox status">{([['active','Active'], ['new','New'], ['saved','Saved'], ['dismissed','Dismissed']] as const).map(([id, label]) => <button role="tab" aria-selected={inboxStatus === id} key={id} onClick={() => setInboxStatus(id)} className={cn("border-b-2 px-3 py-3 text-sm font-medium", inboxStatus === id ? "border-accent text-ink" : "border-transparent text-muted hover:text-ink")}>{label}<span className="ml-2 text-xs opacity-60">{id === "active" ? data.items.filter(i => i.status !== "dismissed").length : data.items.filter(i => i.status === id).length}</span></button>)}</div>
    <div className="mt-4 flex flex-col gap-3 border-b pb-4 sm:flex-row sm:items-center"><div className="relative flex-1"><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-muted" size={16}/><input id="signal-search" value={query} onChange={e => setQuery(e.target.value)} placeholder="Search signals" className="h-10 w-full rounded-lg border bg-surface pl-9 pr-14 text-sm outline-none placeholder:text-muted/70"/><span className="absolute right-3 top-1/2 -translate-y-1/2 rounded border px-1.5 py-0.5 text-[10px] text-muted">/</span></div><div className="flex gap-1 overflow-x-auto">{[["all", "All"], ...data.watchers.map(w => [w.slug, w.name.split(" ")[0]])].map(([id, label]) => <button key={id} onClick={() => setWatcher(id)} className={cn("whitespace-nowrap rounded-lg px-3 py-2 text-xs font-medium", watcher === id ? "bg-ink text-canvas" : "text-muted hover:bg-ink/5")}>{label}</button>)}</div><div className="flex rounded-lg border bg-surface p-1" aria-label="Inbox layout"><button aria-label="List view" aria-pressed={layout === "list"} onClick={() => setLayout("list")} className={cn("rounded-md p-1.5", layout === "list" ? "bg-ink text-canvas" : "text-muted")}><List size={15}/></button><button aria-label="Grid view" aria-pressed={layout === "grid"} onClick={() => setLayout("grid")} className={cn("rounded-md p-1.5", layout === "grid" ? "bg-ink text-canvas" : "text-muted")}><LayoutGrid size={15}/></button></div></div>
    {layout === "list" ? <div className="divide-y">{filtered.map(item => <article key={item.id}><button onClick={() => select(item.id)} className="group grid w-full gap-4 py-5 text-left sm:grid-cols-[112px_minmax(0,1fr)_64px] sm:py-6"><CardImage item={item} compact/><div><div className="flex flex-wrap items-center gap-2 text-[11px] font-medium text-muted"><span className="rounded-full bg-ink/[.05] px-2 py-1">{data.watchers.find(w => w.slug === item.watcher)?.name}</span><span>{item.siteName || relativeTime(item.observedAt)}</span><span>·</span><span>{item.topic}</span></div><h2 className="mt-3 text-base font-semibold leading-6 tracking-[-.01em] group-hover:text-accent sm:text-lg">{item.title}</h2><p className="mt-1.5 line-clamp-2 max-w-3xl text-sm leading-6 text-muted">{item.description}</p></div><div className="flex items-center justify-between sm:block sm:text-right"><span className="text-xs text-muted sm:hidden">Match</span><span className="font-serif text-xl font-semibold">{item.score}</span><ChevronRight className="ml-auto mt-3 hidden text-muted/50 transition-transform group-hover:translate-x-1 sm:block" size={17}/></div></button></article>)}</div> : <div className="grid gap-5 py-6 sm:grid-cols-2 xl:grid-cols-3">{filtered.map(item => <article key={item.id} className="group overflow-hidden rounded-xl border bg-surface shadow-soft"><button onClick={() => select(item.id)} className="w-full text-left"><CardImage item={item}/><div className="p-5"><div className="flex items-center gap-2 text-[11px] text-muted"><span className="truncate">{item.siteName || data.watchers.find(w => w.slug === item.watcher)?.name}</span><span className="ml-auto font-serif text-base font-semibold text-ink">{item.score}</span></div><h2 className="mt-3 line-clamp-2 min-h-12 font-semibold leading-6 group-hover:text-accent">{item.title}</h2><p className="mt-2 line-clamp-3 min-h-[4.5rem] text-sm leading-6 text-muted">{item.description}</p><div className="mt-4 flex items-center gap-2 border-t pt-3 text-[11px] text-muted"><span className="rounded-full bg-ink/[.05] px-2 py-1">{item.topic}</span><span className="ml-auto">{relativeTime(item.observedAt)}</span></div></div></button></article>)}</div>}{filtered.length === 0 && <div className="py-20 text-center"><Archive className="mx-auto text-muted/50"/><p className="mt-4 font-medium">Nothing here</p><p className="mt-1 text-sm text-muted">Try another watcher or search.</p></div>}
  </section>;
}

function CardImage({ item, compact = false }: { item: Signal; compact?: boolean }) { return <div className={cn("relative overflow-hidden bg-gradient-to-br from-accent/15 via-ink/[.04] to-canvas", compact ? "hidden h-20 rounded-lg sm:block" : "aspect-[16/9]")}>{item.image ? <img src={item.image} alt="" loading="lazy" referrerPolicy="no-referrer" onError={event => { event.currentTarget.style.display = "none"; }} className="h-full w-full object-cover transition-transform duration-500 group-hover:scale-[1.03]"/> : <div className="grid h-full place-items-center font-serif text-3xl font-semibold text-ink/25">{(item.siteName || item.watcher).slice(0, 2).toUpperCase()}</div>}</div>; }

function Detail({ item, close, live }: { item: Signal; close: () => void; live: boolean }) {
  const queryClient = useQueryClient();
  const mutation = useMutation({ mutationFn: (status: "new" | "saved" | "dismissed") => live ? updateItem(item.id, status) : Promise.resolve(), onSuccess: () => { queryClient.invalidateQueries({ queryKey: ["workspace"] }); close(); } });
  return <><div className="fixed inset-0 z-40 bg-black/20 backdrop-blur-[2px]" onClick={close}/><aside role="dialog" aria-modal="true" aria-label={item.title} className="fixed inset-y-0 right-0 z-50 w-full overflow-y-auto border-l bg-surface shadow-2xl sm:max-w-xl"><div className="sticky top-0 flex h-16 items-center border-b bg-surface/90 px-5 backdrop-blur"><Button variant="quiet" className="px-2" onClick={close} aria-label="Close"><X size={18}/></Button><span className="ml-2 text-xs text-muted">Signal detail</span></div><div className="px-6 py-8 sm:px-10 sm:py-10"><div className="flex items-center gap-2 text-xs text-muted"><span className="rounded-full bg-accent/10 px-2.5 py-1 font-medium text-accent">{item.topic}</span><span>{relativeTime(item.observedAt)}</span></div><h1 className="mt-5 font-serif text-3xl font-semibold leading-tight tracking-tight sm:text-4xl">{item.title}</h1><p className="mt-5 text-base leading-7 text-muted">{item.description}</p><div className="mt-8 grid grid-cols-2 gap-3 rounded-xl border bg-canvas p-4"><div><p className="text-[11px] uppercase tracking-wider text-muted">Match score</p><p className="mt-1 font-serif text-2xl font-semibold">{item.score}<span className="text-sm text-muted">/100</span></p></div><div><p className="text-[11px] uppercase tracking-wider text-muted">Status</p><p className="mt-2 text-sm font-medium capitalize">{item.status}</p></div></div><div className="mt-9"><h2 className="text-sm font-semibold">Why you are seeing this</h2><div className="mt-3 space-y-3">{item.provenance.map((line, index) => <div key={line} className="flex gap-3 text-sm leading-6 text-muted"><div className="mt-1 grid h-5 w-5 shrink-0 place-items-center rounded-full bg-ink/[.06] text-[10px] font-semibold text-ink">{index + 1}</div>{line}</div>)}</div></div><div className="mt-10 flex gap-2 border-t pt-6">{item.status !== "saved" && <Button variant="accent" onClick={() => mutation.mutate("saved")} disabled={mutation.isPending}><Check size={16}/>Save</Button>}{item.status !== "dismissed" && <Button onClick={() => mutation.mutate("dismissed")} disabled={mutation.isPending}><X size={16}/>Dismiss</Button>}{item.status !== "new" && <Button onClick={() => mutation.mutate("new")} disabled={mutation.isPending}>Restore to inbox</Button>}<a href={item.url} target="_blank" rel="noreferrer" className="ml-auto inline-flex h-9 items-center rounded-lg px-3 text-sm font-medium text-muted hover:bg-ink/5 hover:text-ink">Open source</a></div></div></aside></>;
}

function WatchersView({ data, live }: { data: WorkspaceState; live: boolean }) { const queryClient = useQueryClient(); const mutation = useMutation({ mutationFn: ({ id, enabled }: { id: string; enabled: boolean }) => live ? updateWatcher(id, enabled) : Promise.resolve(), onSuccess: () => queryClient.invalidateQueries({ queryKey: ["workspace"] }) }); return <section className="mx-auto max-w-5xl px-4 py-10 sm:px-7 sm:py-12"><div><p className="text-xs font-semibold uppercase tracking-[.16em] text-accent">Configuration</p><h1 className="mt-2 font-serif text-4xl font-semibold">Watchers</h1><p className="mt-3 text-sm text-muted">Questions that keep observing, even when you are away.</p></div><div className="mt-9 grid gap-4 md:grid-cols-2">{data.watchers.map(w => { const sources = data.sources.filter(source => source.watcher === w.slug); return <article key={w.id} className="rounded-xl border bg-surface p-5 shadow-soft"><div className="flex items-center"><span className={cn("h-2.5 w-2.5 rounded-full", !w.enabled ? "bg-slate-400" : w.status === "attention" ? "bg-amber-500" : "bg-emerald-500")}/><span className="ml-2 text-xs capitalize text-muted">{w.status}</span><Button variant="quiet" className="ml-auto" disabled={mutation.isPending} onClick={() => mutation.mutate({ id: w.id, enabled: !w.enabled })}>{w.enabled ? "Pause" : "Enable"}</Button></div><h2 className="mt-5 font-serif text-2xl font-semibold">{w.name}</h2><p className="mt-2 min-h-12 text-sm leading-6 text-muted">{w.description}</p><details className="group mt-5 border-t pt-4"><summary className="flex cursor-pointer list-none items-center text-xs text-muted"><span>{sources.length || w.sourceCount} sources</span><span className="mx-2">·</span><span>{data.items.filter(i => i.watcher === w.slug).length} signals</span><ChevronRight className="ml-auto transition-transform group-open:rotate-90" size={16}/></summary><div className="mt-4 space-y-2">{sources.map(source => <div key={source.id} className="flex items-center gap-3 rounded-lg bg-canvas px-3 py-2.5"><span className={cn("h-2 w-2 rounded-full", source.status === "ready" ? "bg-emerald-500" : "bg-amber-500")}/><div className="min-w-0 flex-1"><p className="truncate text-xs font-medium">{source.name}</p><p className="mt-0.5 truncate text-[10px] text-muted">{source.discoveryMode} · {source.cadence.replaceAll("_", " ")}</p></div></div>)}</div></details></article>})}</div></section>; }

function DigestsView({ data, live }: { data: WorkspaceState; live: boolean }) { const queryClient = useQueryClient(); const mutation = useMutation({ mutationFn: () => live ? createDigest() : Promise.resolve(), onSuccess: () => queryClient.invalidateQueries({ queryKey: ["workspace"] }) }); return <section className="mx-auto max-w-4xl px-4 py-10 sm:px-7 sm:py-12"><p className="text-xs font-semibold uppercase tracking-[.16em] text-accent">Synthesis</p><div className="mt-2 flex items-end justify-between gap-4"><div><h1 className="font-serif text-4xl font-semibold">Digests</h1><p className="mt-3 text-sm text-muted">Readable summaries of the strongest active signals.</p></div><Button variant="accent" onClick={() => mutation.mutate()} disabled={mutation.isPending}><Plus size={16}/>{mutation.isPending ? "Generating…" : "Generate digest"}</Button></div>{data.digests.length ? <div className="mt-9 space-y-3">{data.digests.map(digest => <article key={digest.id} className="rounded-xl border bg-surface p-6 shadow-soft"><div className="flex items-center gap-2 text-xs text-muted"><BookOpen size={15}/><span>{relativeTime(digest.createdAt)}</span><span>·</span><span>{digest.itemIds.length} highlights</span></div><h2 className="mt-4 font-serif text-2xl font-semibold">{digest.title}</h2><p className="mt-2 text-sm leading-6 text-muted">{digest.summary}</p></article>)}</div> : <Empty icon={BookOpen} title="No digests yet" text="Generate your first brief from the active inbox."/>}</section>; }

function ExportsView({ data, live }: { data: WorkspaceState; live: boolean }) { const queryClient = useQueryClient(); const mutation = useMutation({ mutationFn: () => live ? createExport() : Promise.reject(new Error("Start the local app to export")), onSuccess: (record) => { queryClient.invalidateQueries({ queryKey: ["workspace"] }); window.location.assign(record.downloadUrl); } }); return <section className="mx-auto max-w-4xl px-4 py-10 sm:px-7 sm:py-12"><p className="text-xs font-semibold uppercase tracking-[.16em] text-accent">Portability</p><div className="mt-2 flex items-end justify-between gap-4"><div><h1 className="font-serif text-4xl font-semibold">Exports</h1><p className="mt-3 max-w-xl text-sm leading-6 text-muted">Create a deterministic, hash-verified JSON handoff bundle. Credentials and transient operation data are excluded.</p></div><Button variant="accent" onClick={() => mutation.mutate()} disabled={mutation.isPending}><Download size={16}/>{mutation.isPending ? "Preparing…" : "Create export"}</Button></div>{mutation.isError && <p role="alert" className="mt-4 rounded-lg bg-red-500/10 p-3 text-sm text-red-700">{mutation.error.message}</p>}{data.exports.length ? <div className="mt-9 rounded-xl border bg-surface">{data.exports.map(record => <a key={record.id} href={`/api/v1/exports/${record.filename}`} className="flex items-center gap-4 border-b p-5 last:border-0 hover:bg-ink/[.025]"><div className="grid h-9 w-9 place-items-center rounded-lg bg-accent/10 text-accent"><Download size={17}/></div><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium">{record.filename}</p><p className="mt-1 text-xs text-muted">Revision {record.workspaceRevision} · {relativeTime(record.createdAt)}</p></div><span className="hidden font-mono text-[10px] text-muted sm:block">{record.sha256.slice(0, 12)}…</span></a>)}</div> : <Empty icon={Download} title="No exports yet" text="Your immutable handoff history will appear here."/>}</section>; }

function MembersView() { return <section className="mx-auto max-w-4xl px-4 py-10 sm:px-7 sm:py-12"><p className="text-xs font-semibold uppercase tracking-[.16em] text-accent">Access</p><h1 className="mt-2 font-serif text-4xl font-semibold">Members</h1><p className="mt-3 text-sm text-muted">Local mode has one implicit owner. Hosted collaboration is enabled through PocketBase authentication.</p><div className="mt-9 rounded-xl border bg-surface p-5"><div className="flex items-center gap-4"><div className="grid h-10 w-10 place-items-center rounded-full bg-accent/15 text-sm font-semibold text-accent">YO</div><div><p className="text-sm font-medium">Local owner</p><p className="mt-1 text-xs text-muted">Owner · full workspace access</p></div><span className="ml-auto rounded-full bg-emerald-500/10 px-2.5 py-1 text-xs font-medium text-emerald-700">Active</span></div></div></section>; }

function SettingsView({ dark, setDark }: { dark: boolean; setDark: (value: boolean) => void }) { return <section className="mx-auto max-w-4xl px-4 py-10 sm:px-7 sm:py-12"><p className="text-xs font-semibold uppercase tracking-[.16em] text-accent">Preferences</p><h1 className="mt-2 font-serif text-4xl font-semibold">Workspace settings</h1><div className="mt-9 divide-y rounded-xl border bg-surface"><div className="flex items-center gap-4 p-5"><div className="flex-1"><p className="text-sm font-medium">Dark theme</p><p className="mt-1 text-xs text-muted">Use the lower-light interface on this device.</p></div><Button onClick={() => setDark(!dark)}>{dark ? "Use light" : "Use dark"}</Button></div><div className="p-5"><p className="text-sm font-medium">Immutable JSON storage</p><p className="mt-1 text-xs leading-5 text-muted">Writes are fsynced immediately. Snapshots compact automatically every 100 events or 300 seconds without deleting history.</p></div><div className="p-5"><p className="text-sm font-medium">Local connection</p><p className="mt-1 text-xs text-muted">Loopback only · journal-first durability enabled</p></div></div></section>; }

function Empty({ icon: Icon, title, text }: { icon: typeof Inbox; title: string; text: string }) { return <div className="mt-12 rounded-2xl border border-dashed bg-surface/50 px-6 py-16 text-center"><div className="mx-auto grid h-12 w-12 place-items-center rounded-xl bg-ink/[.05] text-muted"><Icon size={22}/></div><p className="mt-5 font-medium">{title}</p><p className="mt-2 text-sm text-muted">{text}</p></div>; }

function OperationsView({ data }: { data: WorkspaceState }) { return <section className="mx-auto max-w-4xl px-4 py-10 sm:px-7 sm:py-12"><p className="text-xs font-semibold uppercase tracking-[.16em] text-accent">Activity</p><h1 className="mt-2 font-serif text-4xl font-semibold">Operations</h1><p className="mt-3 text-sm text-muted">Runs, imports, exports, and maintenance in one place.</p><div className="mt-9 rounded-xl border bg-surface">{data.operations.map(op => <div key={op.id} className="flex items-center gap-4 border-b p-5 last:border-0"><div className="grid h-9 w-9 place-items-center rounded-full bg-emerald-500/10 text-emerald-600"><Check size={17}/></div><div className="flex-1"><p className="text-sm font-medium">{op.label}</p><p className="mt-1 text-xs capitalize text-muted">{op.status} · {relativeTime(op.updatedAt)}</p></div><span className="text-sm font-medium">{op.progress}%</span></div>)}</div></section>; }

function Placeholder({ title, description, icon: Icon, action }: { title: string; description: string; icon: typeof Inbox; action?: string }) { return <section className="mx-auto max-w-4xl px-4 py-10 sm:px-7 sm:py-12"><p className="text-xs font-semibold uppercase tracking-[.16em] text-accent">Workspace</p><div className="mt-2 flex items-end justify-between gap-4"><div><h1 className="font-serif text-4xl font-semibold">{title}</h1><p className="mt-3 text-sm text-muted">{description}</p></div>{action && <Button variant="accent"><Plus size={16}/>{action}</Button>}</div><div className="mt-12 rounded-2xl border border-dashed bg-surface/50 px-6 py-20 text-center"><div className="mx-auto grid h-12 w-12 place-items-center rounded-xl bg-ink/[.05] text-muted"><Icon size={22}/></div><p className="mt-5 font-medium">Ready when you are</p><p className="mx-auto mt-2 max-w-sm text-sm leading-6 text-muted">This workspace is prepared for {title.toLowerCase()}. Connect the local service to make changes durable.</p></div></section>; }
